### ISSUE TITLE
Scan does not return any objects

### ISSUE THREAD

**Issue by ziggyjosh16** [canix1/ADACLScanner#18]
This error occurs regardless of the filter or scope.:
**Log Error: No objects returned! Does your filter reflect the objects you are looking for?**

The command line outputs this error:
**Cannot bind argument to parameter 'stringList' because it is null**

I also noticed that the Effective Rights scan report does not include the permission. Only the groups, is there a more detailed documentation available for using this tool?

running powershell version 2.0. 
and .Net 4.5

Is there a windows feature that needs to be enabled other than active directory or group policy?
Or maybe another module that needs to be installed?

**Comment by canix1** [comment]
"Log Error: No objects returned! Does your filter reflect the objects you are looking for?"
- What object type have you selected? 

"Cannot bind argument to parameter 'stringList' because it is null"
Since I don't know your command It's hard to tell. I guess it's a PowerShell v 2.0 problem but I do not know. If you have .Net 4.5 why not install WMF 5.0 at least?

"I also noticed that the Effective Rights scan report does not include the permission. Only the groups, is there a more detailed documentation available for using this tool?"
- Are you missing the columns Permissions, ApplyTo in your reports?
- The group represent the security principal choosen . Example: Security prinicpal -> Group - > ACE. The report shows the ACL'ed identity in the column Trustee.

**Comment by ziggyjosh16** [comment]
You are correct in your assumption this program does not work in powershell v2.0 Upgrading fixed all issues
