### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Alex4e4** [canix1/ADACLScanner#37]
Good Day!

please help me, tell me how I can make a report what rights a certain group has in the domain, while leaving only those OUs where the rights are assigned, and not displaying those where the rights are inheritedю Example:
This with Inherited - false save in the report
![Screenshot_50](https://user-images.githubusercontent.com/72306285/128089621-41c35e31-d474-4ba0-a56d-3639c76eadff.jpg)

and this with Inherited - True remove from report
![Screenshot_51](https://user-images.githubusercontent.com/72306285/128089866-3e86e381-9da5-435a-9a22-1079bf82c994.jpg)

I will be glad for any help

**Comment by canix1** [comment]
Hi,

See https://github.com/canix1/ADACLScanner/wiki. I added some examples there.

or try this:
.\ADACLScan.ps1 -b "dc=contoso,dc=com" -EffectiveRightsPrincipal task-user-manage-users -Scope subtree -Output HTML -Show

where
.\ADACLScan.ps1 -b <Your Domain DN> -EffectiveRightsPrincipal <Your Group> -Scope subtree -Output HTML -Show

**Comment by Alex4e4** [comment]
why you closed my post?
your solution shows the same complete report as in my first screenshot. You
gave me what I already did. Apparently you have not read what I wrote

вс, 8 авг. 2021 г. в 01:21, Robin Granberg ***@***.***>:

**Comment by canix1** [comment]
In the GUI go to filter and click Enable Filter .
Under Filter by Trustee:
domain\<group name> like contoso\task-user-manage-users
or
*<group name> like *task-user-manage-users
Then select to search Subtree.

This will not show the effective rights but where this group is explicit added to the ACL.

**Comment by Alex4e4** [comment]
maybe I did not describe it clearly. I ask you to remove the inherited rights from the report, which is displayed in the second image, and you write about how to filter the group from the report

**Comment by canix1** [comment]
Since your pictures does not explain what search you made I can only guess.

I need to ask you the following.

If your group A are member of group B are you then interested in knowing the permissions group B have in the  domain? 

That is what Effective Rights does. The reason for forcing the inheritance when using Effective Rights is that your starting point for the search might have inherited permissions for your principal that you then miss and you would not have the full picture (Effective Rights).

If you are not interested in nested group permission but only your group directly then you use the filter function I explained above and do not check the Inherited Permission check box when searching and without using Effective Rights.

**Comment by canix1** [comment]
Also, an other option for you is that you can select Excel as your output and you can filter whatever you like there too.

**Comment by Alex4e4** [comment]
Thank you, the option with Excel turned out to be what you need

вс, 8 авг. 2021 г. в 11:21, Robin Granberg ***@***.***>:

**Comment by canix1** [comment]
Ok, Great! Nice it worked out for you.
