### ISSUE TITLE
Export CSV

### ISSUE THREAD

**Issue by Bilis518** [canix1/ADACLScanner#47]
Hello,

Actually if you open a csv in Excel, then convert data with default ',' you will have an issue with the OU path containing ','.
I advise to add a delimiter when export-csv.
It is easier when you use a csv in Excel.

export-csv -delimiter ';'

**Comment by canix1** [comment]
Hi,

I know the struggle with importing in Excel and have had the same problem.

It is really annoying when Excel doesn't do it right sometimes when click on a file or open it directly.

**Make sure your language settings in Office have comma as the default separator.**

But this is already solved.

I can just double-click the file or open it within Excel and it just works.

Why?
- The data is kept within quotation mark, so Excel understands it.
- It should be comma since it is a (Comma Separated Values) file.
- You are not doing it right.

This is the correct way to import a CSV-file to Excel. 

1. Open Excel
2. New File
3. Tab "Data" -> From Text/CSV
4. Select CSV file
5. Click Load 
6. Done!

Or with PowerShell
`import-csv -Path "managedpriv_MANAGEDPRIV_adAclOutput20220806_104856.csv" | Export-Excel -Path .\MyExcelFile.xlsx`
